# Opteryx Labs - 101.01 - Simple Query & Display

Welcome to the first lab in the [Opteryx Labs](https://github.com/mabel-dev/labs) series! In this session, you'll take your first steps into the world of SQL querying with [Opteryx](https://github.com/mabel-dev/opteryx). Whether youâ€™re a data science enthusiast, a professional looking to sharpen your SQL skills, or a student eager to dive into the basics of data manipulation, this lab is designed to provide you with a solid foundation.

**What You Will Learn and Do:**

- Start by installing the Opteryx package. We'll guide you through every step, ensuring that Opteryx is set up properly in your environment.
- Learn how to import the Opteryx library into your Python script or Jupyter notebook. This step is crucial for all subsequent operations with Opteryx.
- Discover how to craft and execute a straightforward SQL query. You'll get hands-on experience with the syntax and capabilities of Opteryx.
- Understand how to retrieve and display the results of your queries. Seeing the output will help you grasp the immediate impact of the queries you write.

**Getting Started**

Before jumping into the coding, make sure you have a Python environment ready for use. This can be a local setup on your computer or a cloud-based Jupyter notebook. Don't worry if you're new to this; we'll walk you through everything you need to know.

**Take Off!**

Letâ€™s start our journey into the world of data querying with Opteryx!

In [ ]:
# Ensure that Opteryx is installed in the current Jupyter kernel
import sys
!{sys.executable} -m pip install opteryx

In [ ]:
# Import the Opteryx Library
import opteryx

# Define SQL Statement
"""
Defines the SQL query to be executed. In this example, we're selecting all
columns from the internal dataset named $planets.
"""
sql_statement: str = "SELECT * FROM $planets;"

# Execute the SQL Query and Store the Results
"""
This function call both executes the SQL query and retrieves the results.
"""
results = opteryx.query(sql_statement)

# Display the Results
"""
Displays up to 10 rows of the results. This will provide you with a snapshot of
the data you queried for.

Note that there's only 9 planets, so only 9 rows are returned in this example
"""
results

# Great Job!

You've successfully executed your first SQL query using Opteryx and displayed the results! This is a simple example, but it opens the door to a multitude of possibilities.

**Level Up Your Skills ðŸš€**

- Why stop at `$planets`? Take a spacewalk through other internal datasets like `$satellites` or `$astronauts`.
- Unleash your inner data explorer by playing around with different SQL commandsâ€”sort, filter, and aggregate to your heart's content!
- Craving more power? Check out [Opteryx's documentation](https://opteryx.dev/latest/) to unlock more advanced features!
- So go ahead, take the controls and boldly query where no one has queried before!