# Opteryx Example - Simple Query & Display

In this Notebook we're going to execute a simple SQL query using Opteryx against an internal sample dataset.

In [ ]:
!pip install --upgrade --quiet opteryx

In [ ]:
import opteryx

In [ ]:
# define our SQL statement
sql_statement = "SELECT * FROM $planets;"

# Create a connection, as $planets is an internal dataset we don't need to configure the connection
conn = opteryx.connect()

# create a database cursor
cursor = conn.cursor()

# execute our SQL statement
cursor.execute(sql_statement)

# display the first 10 results
cursor.head()